/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["src/**/*.{njk,html,md,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e4e2e2",
        "secondary-container": "#7dd0ff",
        "on-surface": "#1b1c1c",
        "inverse-surface": "#303031",
        "secondary-fixed": "#c4e7ff",
        "on-background": "#1b1c1c",
        "tertiary-fixed": "#bbf45c",
        "surface-dim": "#dbdad9",
        "on-primary-container": "#004566",
        "tertiary-container": "#87bc28",
        error: "#ba1a1a",
        "surface-tint": "#006493",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#8ccdff",
        "on-tertiary-container": "#2f4700",
        "surface-container-lowest": "#ffffff",
        secondary: "#00658b",
        "secondary-fixed-dim": "#7dd0ff",
        "tertiary-fixed-dim": "#a0d743",
        "on-error-container": "#93000a",
        "outline-variant": "#bec8d2",
        "surface-variant": "#e4e2e2",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#3e4850",
        "on-secondary-fixed": "#001e2c",
        "on-tertiary-fixed": "#121f00",
        "inverse-primary": "#8ccdff",
        "on-secondary-fixed-variant": "#004c69",
        "inverse-on-surface": "#f2f0f0",
        "primary-fixed": "#cae6ff",
        "error-container": "#ffdad6",
        "primary-container": "#38b6ff",
        "surface-container-low": "#f5f3f3",
        background: "#fbf9f8",
        primary: "#006493",
        "surface-container-high": "#e9e8e7",
        "on-primary-fixed": "#001e30",
        tertiary: "#4d7a00",
        "on-error": "#ffffff",
        "on-secondary-container": "#004b67",
        outline: "#6e7882",
        "surface-bright": "#fbf9f8",
        "on-tertiary-fixed-variant": "#344e00",
        "on-secondary": "#ffffff",
        "surface-container": "#efeded",
        surface: "#fbf9f8",
        "on-primary-fixed-variant": "#004b70",
        "accent-orange": "#fc610f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Work Sans"],
        label: ["Work Sans"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
